server:
  port: 8090
  servlet:
    context-path: /consumer-demo

springbootURL:
  baseURL: http://localhost:8080/springootbasic
  saveEmployee: /v1/rest/employee

spring:
  config:
    import: "optional:configserver:"
  application:
    name: CONSUMER-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    config:
      uri:
      - http://localhost:9196/
management:
  health:
    show-details: always
    circuitbreakers:
      enabled: true
  endpoints:
    exposure:
      include: health,info,circuitbreakers